window.esdocSearchIndex = [
  [
    "connecting-bits/js/index.js~boardschain",
    "class/js/index.js~BoardsChain.html",
    "<span>BoardsChain</span> <span class=\"search-result-import-path\">connecting-bits/js/index.js</span>",
    "class"
  ],
  [
    "connecting-bits/js/components/box/index.js~box",
    "class/js/components/box/index.js~Box.html",
    "<span>Box</span> <span class=\"search-result-import-path\">connecting-bits/js/components/box/index.js</span>",
    "class"
  ],
  [
    "connecting-bits/js/components/microphone/utils/reports/index.js~createreport",
    "class/js/components/microphone/utils/reports/index.js~CreateReport.html",
    "<span>CreateReport</span> <span class=\"search-result-import-path\">connecting-bits/js/components/microphone/utils/reports/index.js</span>",
    "class"
  ],
  [
    "connecting-bits/js/components/dummymicrophone/index.js~dummymicrophone",
    "class/js/components/dummyMicrophone/index.js~DummyMicrophone.html",
    "<span>DummyMicrophone</span> <span class=\"search-result-import-path\">connecting-bits/js/components/dummyMicrophone/index.js</span>",
    "class"
  ],
  [
    "connecting-bits/js/constants/index.js~infrared_constants",
    "variable/index.html#static-variable-INFRARED_CONSTANTS",
    "<span>INFRARED_CONSTANTS</span> <span class=\"search-result-import-path\">connecting-bits/js/constants/index.js</span>",
    "variable"
  ],
  [
    "connecting-bits/js/components/infrared/index.js~intrared",
    "class/js/components/infrared/index.js~Intrared.html",
    "<span>Intrared</span> <span class=\"search-result-import-path\">connecting-bits/js/components/infrared/index.js</span>",
    "class"
  ],
  [
    "connecting-bits/js/constants/index.js~light_constants",
    "variable/index.html#static-variable-LIGHT_CONSTANTS",
    "<span>LIGHT_CONSTANTS</span> <span class=\"search-result-import-path\">connecting-bits/js/constants/index.js</span>",
    "variable"
  ],
  [
    "connecting-bits/js/components/light/index.js~light",
    "class/js/components/light/index.js~Light.html",
    "<span>Light</span> <span class=\"search-result-import-path\">connecting-bits/js/components/light/index.js</span>",
    "class"
  ],
  [
    "connecting-bits/js/constants/index.js~motor_constants",
    "variable/index.html#static-variable-MOTOR_CONSTANTS",
    "<span>MOTOR_CONSTANTS</span> <span class=\"search-result-import-path\">connecting-bits/js/constants/index.js</span>",
    "variable"
  ],
  [
    "connecting-bits/js/components/motor/index.js~motor",
    "class/js/components/motor/index.js~Motor.html",
    "<span>Motor</span> <span class=\"search-result-import-path\">connecting-bits/js/components/motor/index.js</span>",
    "class"
  ],
  [
    "connecting-bits/js/components/microphone/utils/records/index.js~record",
    "class/js/components/microphone/utils/records/index.js~Record.html",
    "<span>Record</span> <span class=\"search-result-import-path\">connecting-bits/js/components/microphone/utils/records/index.js</span>",
    "class"
  ],
  [
    "connecting-bits/js/components/speaker/index.js~speaker",
    "class/js/components/speaker/index.js~Speaker.html",
    "<span>Speaker</span> <span class=\"search-result-import-path\">connecting-bits/js/components/speaker/index.js</span>",
    "class"
  ],
  [
    "connecting-bits/js/components/microphone/index.js~translator",
    "class/js/components/microphone/index.js~Translator.html",
    "<span>Translator</span> <span class=\"search-result-import-path\">connecting-bits/js/components/microphone/index.js</span>",
    "class"
  ],
  [
    "connecting-bits/js/components/translator/index.js~translator",
    "class/js/components/translator/index.js~Translator.html",
    "<span>Translator</span> <span class=\"search-result-import-path\">connecting-bits/js/components/translator/index.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "js/components/box/index.js",
    "file/js/components/box/index.js.html",
    "js/components/box/index.js",
    "file"
  ],
  [
    "js/components/box/index.js~box#board",
    "class/js/components/box/index.js~Box.html#instance-member-board",
    "js/components/box/index.js~Box#board",
    "member"
  ],
  [
    "js/components/box/index.js~box#client",
    "class/js/components/box/index.js~Box.html#instance-member-client",
    "js/components/box/index.js~Box#client",
    "member"
  ],
  [
    "js/components/box/index.js~box#constructor",
    "class/js/components/box/index.js~Box.html#instance-constructor-constructor",
    "js/components/box/index.js~Box#constructor",
    "method"
  ],
  [
    "js/components/box/index.js~box#finish",
    "class/js/components/box/index.js~Box.html#instance-method-finish",
    "js/components/box/index.js~Box#finish",
    "method"
  ],
  [
    "js/components/box/index.js~box#getboard",
    "class/js/components/box/index.js~Box.html#instance-method-getBoard",
    "js/components/box/index.js~Box#getBoard",
    "method"
  ],
  [
    "js/components/box/index.js~box#getclient",
    "class/js/components/box/index.js~Box.html#instance-method-getClient",
    "js/components/box/index.js~Box#getClient",
    "method"
  ],
  [
    "js/components/box/index.js~box#infrared",
    "class/js/components/box/index.js~Box.html#instance-member-infrared",
    "js/components/box/index.js~Box#infrared",
    "member"
  ],
  [
    "js/components/box/index.js~box#islastround",
    "class/js/components/box/index.js~Box.html#instance-method-isLastRound",
    "js/components/box/index.js~Box#isLastRound",
    "method"
  ],
  [
    "js/components/box/index.js~box#light",
    "class/js/components/box/index.js~Box.html#instance-member-light",
    "js/components/box/index.js~Box#light",
    "member"
  ],
  [
    "js/components/box/index.js~box#microphone",
    "class/js/components/box/index.js~Box.html#instance-member-microphone",
    "js/components/box/index.js~Box#microphone",
    "member"
  ],
  [
    "js/components/box/index.js~box#motor",
    "class/js/components/box/index.js~Box.html#instance-member-motor",
    "js/components/box/index.js~Box#motor",
    "member"
  ],
  [
    "js/components/box/index.js~box#name",
    "class/js/components/box/index.js~Box.html#instance-member-name",
    "js/components/box/index.js~Box#name",
    "member"
  ],
  [
    "js/components/box/index.js~box#onboardready",
    "class/js/components/box/index.js~Box.html#instance-method-onBoardReady",
    "js/components/box/index.js~Box#onBoardReady",
    "method"
  ],
  [
    "js/components/box/index.js~box#onconnect",
    "class/js/components/box/index.js~Box.html#instance-method-onConnect",
    "js/components/box/index.js~Box#onConnect",
    "method"
  ],
  [
    "js/components/box/index.js~box#onmessage",
    "class/js/components/box/index.js~Box.html#instance-method-onMessage",
    "js/components/box/index.js~Box#onMessage",
    "method"
  ],
  [
    "js/components/box/index.js~box#onpresencedetected",
    "class/js/components/box/index.js~Box.html#instance-method-onPresenceDetected",
    "js/components/box/index.js~Box#onPresenceDetected",
    "method"
  ],
  [
    "js/components/box/index.js~box#onpreviousboxspeaking",
    "class/js/components/box/index.js~Box.html#instance-method-onPreviousBoxSpeaking",
    "js/components/box/index.js~Box#onPreviousBoxSpeaking",
    "method"
  ],
  [
    "js/components/box/index.js~box#onrecordingfailed",
    "class/js/components/box/index.js~Box.html#instance-method-onRecordingFailed",
    "js/components/box/index.js~Box#onRecordingFailed",
    "method"
  ],
  [
    "js/components/box/index.js~box#onrulesexplained",
    "class/js/components/box/index.js~Box.html#instance-method-onRulesExplained",
    "js/components/box/index.js~Box#onRulesExplained",
    "method"
  ],
  [
    "js/components/box/index.js~box#ontextspoken",
    "class/js/components/box/index.js~Box.html#instance-method-onTextSpoken",
    "js/components/box/index.js~Box#onTextSpoken",
    "method"
  ],
  [
    "js/components/box/index.js~box#options",
    "class/js/components/box/index.js~Box.html#instance-member-options",
    "js/components/box/index.js~Box#options",
    "member"
  ],
  [
    "js/components/box/index.js~box#preparetospeak",
    "class/js/components/box/index.js~Box.html#instance-method-prepareToSpeak",
    "js/components/box/index.js~Box#prepareToSpeak",
    "method"
  ],
  [
    "js/components/box/index.js~box#restarttheshow",
    "class/js/components/box/index.js~Box.html#instance-method-restartTheShow",
    "js/components/box/index.js~Box#restartTheShow",
    "method"
  ],
  [
    "js/components/box/index.js~box#round",
    "class/js/components/box/index.js~Box.html#instance-member-round",
    "js/components/box/index.js~Box#round",
    "member"
  ],
  [
    "js/components/box/index.js~box#sendmessage",
    "class/js/components/box/index.js~Box.html#instance-method-sendMessage",
    "js/components/box/index.js~Box#sendMessage",
    "method"
  ],
  [
    "js/components/box/index.js~box#speaktext",
    "class/js/components/box/index.js~Box.html#instance-method-speakText",
    "js/components/box/index.js~Box#speakText",
    "method"
  ],
  [
    "js/components/box/index.js~box#speaker",
    "class/js/components/box/index.js~Box.html#instance-member-speaker",
    "js/components/box/index.js~Box#speaker",
    "member"
  ],
  [
    "js/components/box/index.js~box#start",
    "class/js/components/box/index.js~Box.html#instance-method-start",
    "js/components/box/index.js~Box#start",
    "method"
  ],
  [
    "js/components/box/index.js~box#starttheshow",
    "class/js/components/box/index.js~Box.html#instance-method-startTheShow",
    "js/components/box/index.js~Box#startTheShow",
    "method"
  ],
  [
    "js/components/box/index.js~box#translator",
    "class/js/components/box/index.js~Box.html#instance-member-translator",
    "js/components/box/index.js~Box#translator",
    "member"
  ],
  [
    "js/components/dummymicrophone/index.js",
    "file/js/components/dummyMicrophone/index.js.html",
    "js/components/dummyMicrophone/index.js",
    "file"
  ],
  [
    "js/components/dummymicrophone/index.js~dummymicrophone#startrecording",
    "class/js/components/dummyMicrophone/index.js~DummyMicrophone.html#instance-method-startRecording",
    "js/components/dummyMicrophone/index.js~DummyMicrophone#startRecording",
    "method"
  ],
  [
    "js/components/infrared/index.js",
    "file/js/components/infrared/index.js.html",
    "js/components/infrared/index.js",
    "file"
  ],
  [
    "js/components/infrared/index.js~intrared#board",
    "class/js/components/infrared/index.js~Intrared.html#instance-member-board",
    "js/components/infrared/index.js~Intrared#board",
    "member"
  ],
  [
    "js/components/infrared/index.js~intrared#checklaterifstillpresent",
    "class/js/components/infrared/index.js~Intrared.html#instance-method-checkLaterIfStillPresent",
    "js/components/infrared/index.js~Intrared#checkLaterIfStillPresent",
    "method"
  ],
  [
    "js/components/infrared/index.js~intrared#constructor",
    "class/js/components/infrared/index.js~Intrared.html#instance-constructor-constructor",
    "js/components/infrared/index.js~Intrared#constructor",
    "method"
  ],
  [
    "js/components/infrared/index.js~intrared#debouncedcheck",
    "class/js/components/infrared/index.js~Intrared.html#instance-member-debouncedCheck",
    "js/components/infrared/index.js~Intrared#debouncedCheck",
    "member"
  ],
  [
    "js/components/infrared/index.js~intrared#detectpresence",
    "class/js/components/infrared/index.js~Intrared.html#instance-method-detectPresence",
    "js/components/infrared/index.js~Intrared#detectPresence",
    "method"
  ],
  [
    "js/components/infrared/index.js~intrared#distance",
    "class/js/components/infrared/index.js~Intrared.html#instance-member-distance",
    "js/components/infrared/index.js~Intrared#distance",
    "member"
  ],
  [
    "js/components/infrared/index.js~intrared#getinitializedproximity",
    "class/js/components/infrared/index.js~Intrared.html#instance-method-getInitializedProximity",
    "js/components/infrared/index.js~Intrared#getInitializedProximity",
    "method"
  ],
  [
    "js/components/infrared/index.js~intrared#ondata",
    "class/js/components/infrared/index.js~Intrared.html#instance-method-onData",
    "js/components/infrared/index.js~Intrared#onData",
    "method"
  ],
  [
    "js/components/infrared/index.js~intrared#presencedetected",
    "class/js/components/infrared/index.js~Intrared.html#instance-member-presenceDetected",
    "js/components/infrared/index.js~Intrared#presenceDetected",
    "member"
  ],
  [
    "js/components/infrared/index.js~intrared#proximity",
    "class/js/components/infrared/index.js~Intrared.html#instance-member-proximity",
    "js/components/infrared/index.js~Intrared#proximity",
    "member"
  ],
  [
    "js/components/infrared/index.js~intrared#resolve",
    "class/js/components/infrared/index.js~Intrared.html#instance-member-resolve",
    "js/components/infrared/index.js~Intrared#resolve",
    "member"
  ],
  [
    "js/components/light/index.js",
    "file/js/components/light/index.js.html",
    "js/components/light/index.js",
    "file"
  ],
  [
    "js/components/light/index.js~light#constructor",
    "class/js/components/light/index.js~Light.html#instance-constructor-constructor",
    "js/components/light/index.js~Light#constructor",
    "method"
  ],
  [
    "js/components/light/index.js~light#led",
    "class/js/components/light/index.js~Light.html#instance-member-led",
    "js/components/light/index.js~Light#led",
    "member"
  ],
  [
    "js/components/light/index.js~light#startblinking",
    "class/js/components/light/index.js~Light.html#instance-method-startBlinking",
    "js/components/light/index.js~Light#startBlinking",
    "method"
  ],
  [
    "js/components/light/index.js~light#stopblinking",
    "class/js/components/light/index.js~Light.html#instance-method-stopBlinking",
    "js/components/light/index.js~Light#stopBlinking",
    "method"
  ],
  [
    "js/components/microphone/index.js",
    "file/js/components/microphone/index.js.html",
    "js/components/microphone/index.js",
    "file"
  ],
  [
    "js/components/microphone/index.js~translator#constructor",
    "class/js/components/microphone/index.js~Translator.html#instance-constructor-constructor",
    "js/components/microphone/index.js~Translator#constructor",
    "method"
  ],
  [
    "js/components/microphone/index.js~translator#getaudiodata",
    "class/js/components/microphone/index.js~Translator.html#instance-method-getAudioData",
    "js/components/microphone/index.js~Translator#getAudioData",
    "method"
  ],
  [
    "js/components/microphone/index.js~translator#reportaudio",
    "class/js/components/microphone/index.js~Translator.html#instance-method-reportAudio",
    "js/components/microphone/index.js~Translator#reportAudio",
    "method"
  ],
  [
    "js/components/microphone/index.js~translator#startrecording",
    "class/js/components/microphone/index.js~Translator.html#instance-method-startRecording",
    "js/components/microphone/index.js~Translator#startRecording",
    "method"
  ],
  [
    "js/components/microphone/utils/records/index.js",
    "file/js/components/microphone/utils/records/index.js.html",
    "js/components/microphone/utils/records/index.js",
    "file"
  ],
  [
    "js/components/microphone/utils/records/index.js~record#constructor",
    "class/js/components/microphone/utils/records/index.js~Record.html#instance-constructor-constructor",
    "js/components/microphone/utils/records/index.js~Record#constructor",
    "method"
  ],
  [
    "js/components/microphone/utils/reports/index.js",
    "file/js/components/microphone/utils/reports/index.js.html",
    "js/components/microphone/utils/reports/index.js",
    "file"
  ],
  [
    "js/components/microphone/utils/reports/index.js~createreport#constructor",
    "class/js/components/microphone/utils/reports/index.js~CreateReport.html#instance-constructor-constructor",
    "js/components/microphone/utils/reports/index.js~CreateReport#constructor",
    "method"
  ],
  [
    "js/components/microphone/utils/reports/index.js~createreport#data",
    "class/js/components/microphone/utils/reports/index.js~CreateReport.html#instance-member-data",
    "js/components/microphone/utils/reports/index.js~CreateReport#data",
    "member"
  ],
  [
    "js/components/microphone/utils/reports/index.js~createreport#extendjson",
    "class/js/components/microphone/utils/reports/index.js~CreateReport.html#instance-method-extendJSON",
    "js/components/microphone/utils/reports/index.js~CreateReport#extendJSON",
    "method"
  ],
  [
    "js/components/microphone/utils/reports/index.js~createreport#filepath",
    "class/js/components/microphone/utils/reports/index.js~CreateReport.html#instance-member-filePath",
    "js/components/microphone/utils/reports/index.js~CreateReport#filePath",
    "member"
  ],
  [
    "js/components/microphone/utils/reports/index.js~createreport#newobject",
    "class/js/components/microphone/utils/reports/index.js~CreateReport.html#instance-member-newObject",
    "js/components/microphone/utils/reports/index.js~CreateReport#newObject",
    "member"
  ],
  [
    "js/components/microphone/utils/reports/index.js~createreport#writejson",
    "class/js/components/microphone/utils/reports/index.js~CreateReport.html#instance-method-writeJSON",
    "js/components/microphone/utils/reports/index.js~CreateReport#writeJSON",
    "method"
  ],
  [
    "js/components/microphone/utils/speechtotext/index.js",
    "file/js/components/microphone/utils/speechtotext/index.js.html",
    "js/components/microphone/utils/speechtotext/index.js",
    "file"
  ],
  [
    "js/components/motor/index.js",
    "file/js/components/motor/index.js.html",
    "js/components/motor/index.js",
    "file"
  ],
  [
    "js/components/motor/index.js~motor#checkandmove",
    "class/js/components/motor/index.js~Motor.html#instance-method-checkAndMove",
    "js/components/motor/index.js~Motor#checkAndMove",
    "method"
  ],
  [
    "js/components/motor/index.js~motor#constructor",
    "class/js/components/motor/index.js~Motor.html#instance-constructor-constructor",
    "js/components/motor/index.js~Motor#constructor",
    "method"
  ],
  [
    "js/components/motor/index.js~motor#liedown",
    "class/js/components/motor/index.js~Motor.html#instance-method-lieDown",
    "js/components/motor/index.js~Motor#lieDown",
    "method"
  ],
  [
    "js/components/motor/index.js~motor#liftservo",
    "class/js/components/motor/index.js~Motor.html#instance-member-liftServo",
    "js/components/motor/index.js~Motor#liftServo",
    "member"
  ],
  [
    "js/components/motor/index.js~motor#lookstraight",
    "class/js/components/motor/index.js~Motor.html#instance-method-lookStraight",
    "js/components/motor/index.js~Motor#lookStraight",
    "method"
  ],
  [
    "js/components/motor/index.js~motor#lookup",
    "class/js/components/motor/index.js~Motor.html#instance-method-lookUp",
    "js/components/motor/index.js~Motor#lookUp",
    "method"
  ],
  [
    "js/components/motor/index.js~motor#standup",
    "class/js/components/motor/index.js~Motor.html#instance-method-standUp",
    "js/components/motor/index.js~Motor#standUp",
    "method"
  ],
  [
    "js/components/motor/index.js~motor#stands",
    "class/js/components/motor/index.js~Motor.html#instance-member-stands",
    "js/components/motor/index.js~Motor#stands",
    "member"
  ],
  [
    "js/components/motor/index.js~motor#tiltservo",
    "class/js/components/motor/index.js~Motor.html#instance-member-tiltServo",
    "js/components/motor/index.js~Motor#tiltServo",
    "member"
  ],
  [
    "js/components/motor/index.js~motor#titls",
    "class/js/components/motor/index.js~Motor.html#instance-member-titls",
    "js/components/motor/index.js~Motor#titls",
    "member"
  ],
  [
    "js/components/speaker/index.js",
    "file/js/components/speaker/index.js.html",
    "js/components/speaker/index.js",
    "file"
  ],
  [
    "js/components/speaker/index.js~speaker#explainrules",
    "class/js/components/speaker/index.js~Speaker.html#instance-method-explainRules",
    "js/components/speaker/index.js~Speaker#explainRules",
    "method"
  ],
  [
    "js/components/speaker/index.js~speaker#saynorecordingerror",
    "class/js/components/speaker/index.js~Speaker.html#instance-method-sayNoRecordingError",
    "js/components/speaker/index.js~Speaker#sayNoRecordingError",
    "method"
  ],
  [
    "js/components/speaker/index.js~speaker#speaktext",
    "class/js/components/speaker/index.js~Speaker.html#instance-method-speakText",
    "js/components/speaker/index.js~Speaker#speakText",
    "method"
  ],
  [
    "js/components/translator/index.js",
    "file/js/components/translator/index.js.html",
    "js/components/translator/index.js",
    "file"
  ],
  [
    "js/components/translator/index.js~translator#translatetext",
    "class/js/components/translator/index.js~Translator.html#instance-method-translateText",
    "js/components/translator/index.js~Translator#translateText",
    "method"
  ],
  [
    "js/constants/index.js",
    "file/js/constants/index.js.html",
    "js/constants/index.js",
    "file"
  ],
  [
    "js/index.js",
    "file/js/index.js.html",
    "js/index.js",
    "file"
  ],
  [
    "js/index.js~boardschain#boxes",
    "class/js/index.js~BoardsChain.html#instance-member-boxes",
    "js/index.js~BoardsChain#boxes",
    "member"
  ],
  [
    "js/index.js~boardschain#constructor",
    "class/js/index.js~BoardsChain.html#instance-constructor-constructor",
    "js/index.js~BoardsChain#constructor",
    "method"
  ],
  [
    "js/index.js~boardschain#masterbox",
    "class/js/index.js~BoardsChain.html#instance-member-masterBox",
    "js/index.js~BoardsChain#masterBox",
    "member"
  ],
  [
    "js/index.js~boardschain#onallboardsready",
    "class/js/index.js~BoardsChain.html#instance-method-onAllBoardsReady",
    "js/index.js~BoardsChain#onAllBoardsReady",
    "method"
  ],
  [
    "js/utils/boardsutil.js",
    "file/js/utils/boardsUtil.js.html",
    "js/utils/boardsUtil.js",
    "file"
  ],
  [
    "js/utils/clientsutil.js",
    "file/js/utils/clientsUtil.js.html",
    "js/utils/clientsUtil.js",
    "file"
  ],
  [
    "js/utils/logutil.js",
    "file/js/utils/logUtil.js.html",
    "js/utils/logUtil.js",
    "file"
  ]
]